### ISSUE TITLE
Obsoletion notice: GO terms associated with transferred ECs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go_announcements#629]
Dear all, 

The proposal has been made to obsolete the following terms, with replaced_by as indicated: 

Obsolete GO:0050245 quercitrinase activity (EC:3.2.1.66 Transferred to EC:3.2.1.40 ; replace by GO:0030596 alpha-L-rhamnosidase activity (EC:3.2.1.40)  (no annotations)

Obsolete GO:0047409 alkenylglycerophosphoethanolamine hydrolase activity (EC:3.3.2.5 transferred to EC:3.3.2.2);  replace by GO:0047408 alkenylglycerophosphocholine hydrolase activity (EC:3.3.2.2) (genes annotated to GO:0047409 are also annotated to GO:0047408)

Obsolete GO:0047702 beta-lysine 5,6-aminomutase activity (EC:5.4.3.4 Transferred to EC:5.4.3.3; replace by GO:0047826 D-lysine 5,6-aminomutase activity (EC:5.4.3.3) (no annotations)

The reason for obsoletion is that the EC numbers associated with the GO terms to be obsoleted have been replaced by ECs that are associated with the terms proposed to replace the obsolete terms. Other cross-references will be moved as appropriate. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24927

Thanks, Pascale

**Comment by sjm41** [comment]
Hi @pgaudet 

I think there was a paste-o with the 'replaced_by' term for GO:0047409 - it should have been GO:0047408 (as per your comment above), but 'GO:0047826' was used instead (which is for one of the other terms mentioned above).

So, for example, the annotation on UniProtKB:Q8N661 was changed to 'GO:0047826 D-lysine 5,6-aminomutase activity", which is wrong.

Can you fix?


[Term]
id: GO:0047409
name: obsolete alkenylglycerophosphoethanolamine hydrolase activity
namespace: molecular_function
def: "OBSOLETE. Catalysis of the reaction: H2O + 1-(1-alkenyl)-sn-glycero-3-phosphoethanolamine = sn-glycero-3-phosphoethanolamine + an aldehyde." [EC:3.3.2.5, MetaCyc:3.3.2.5-RXN]
comment: This term was obsoleted because the EC number to which it was associated was transferred to EC:3.3.2.2; which corresponds to alkenylglycerophosphocholine hydrolase activity ; GO:0047408.
synonym: "1-(1-alkenyl)-sn-glycero-3-phosphoethanolamine aldehydohydrolase activity" RELATED [EC:3.3.2.5]
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/24927" xsd:anyURI
is_obsolete: true
replaced_by: GO:0047826

**Comment by sjm41** [comment]
@pgaudet Just checking you saw this?
